#index:
#    path: /
#    controller: App\Controller\DefaultController::index
controllers:
    resource: '../src/Controller/'
    type:     annotation
fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
