twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        "%kernel.project_dir%/public": public_path
        "%kernel.project_dir%/templates/bundles": sonataBundles
        "%kernel.project_dir%/templates": View

    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    # exception_controller: App\Controller\xFrontController::ErrorRedirect


