#index:
#    path: /
#    controller: App\Controller\DefaultController::index
controllers:
    resource: '../src/Controller/'
    type:     annotation
fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"


gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery
media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

